version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: panel_webclient
    volumes:
      - ./data:/ql/data
    ports:
      - "0.0.0.0:5700:5700"
    restart: unless-stopped
